name: Sync Nodes from Server

on:
schedule:
    # 北京时间 20:00 = UTC 12:00
    # cron 格式: 分 时 日 月 周
    - cron: '0 12 * * *'
  workflow_dispatch:      # 允许你在 GitHub 网页上手动点击按钮触发同步

jobs:
  sync_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch files from my server
        run: |
          # 添加 -f 确保失败时停止脚本
          curl -f -o v2ray.txt "${{ secrets.URL }}?v=${{ secrets.TOKEN }}"
          curl -f -o clash.txt "${{ secrets.URL }}?c=${{ secrets.TOKEN }}"
          curl -f -o v2ray_check.txt "${{ secrets.URL }}?vc=${{ secrets.TOKEN }}"
          curl -f -o clash_check.txt "${{ secrets.URL }}?cc=${{ secrets.TOKEN }}"

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # 只添加我们要更新的这 4 个特定文件
          git add v2ray.txt clash.txt v2ray_check.txt clash_check.txt
          # 如果文件有变动，则自动提交并推送到仓库
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-sync: update node files from server" && git push)
